version: '2' services:
    
    portainer:
        restart: always
        container_name: Portainer
        expose:
            - "9000"
        ports:
            - "1000:9000"
        image: portainer/portainer
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer/portainer_data:/data
